### ISSUE TITLE
json解析异常是我的原因吗，

### ISSUE THREAD

**Issue by SQLKILL** [imtsuki/bupt-ncov-report-action#31]
![Uploading image.png…]()

**Comment by SQLKILL** [comment]
```
yarn run v1.22.11
$ /home/runner/work/bupt-ncov-report-action/bupt-ncov-report-action/node_modules/.bin/ts-node src/index.ts
Mon, 13 Sep 2021 03:18:14 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. at internal/modules/cjs/loader.js:999:30
用户登录中
Sleep for 1120ms...
正在获取前一天的疫情填报信息
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /home/runner/work/bupt-ncov-report-action/bupt-ncov-report-action/src/index.ts:44:43
    at step (/home/runner/work/bupt-ncov-report-action/bupt-ncov-report-action/src/index.ts:52:23)
    at Object.next (/home/runner/work/bupt-ncov-report-action/bupt-ncov-report-action/src/index.ts:33:53)
    at fulfilled (/home/runner/work/bupt-ncov-report-action/bupt-ncov-report-action/src/index.ts:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Unexpected end of JSON input
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.

```

**Comment by ksqytl** [comment]
老哥，我也是这样的问题，你解决了吗
