### ISSUE TITLE
Error: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Looong01** [imtsuki/bupt-ncov-report-action#63]
正在获取前一天的疫情填报信息
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getDailyReportFormData (file:///home/runner/work/bupt-ncov-report-action/bupt-ncov-report-action/src/index.ts:71:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///home/runner/work/bupt-ncov-report-action/bupt-ncov-report-action/src/index.ts:145:22
Error: Unexpected end of JSON input
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.

**Comment by imtsuki** [comment]
手动更新一次，明天再试
